name: "Release automatic"

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: false
          title: "Release ${{ env.GITHUB_REF }}"
          files: |
            LICENSE.txt
            *.js
            *.xml
            *.json
            *.txt
            *.*
            **.*
            **.**
            *.**
